### ISSUE TITLE
Hvornår fortages udtræk af spørgsmål?

### ISSUE THREAD

**Issue by mathwro** [CphBusCosSem2/EksamensInfo#1]
Specielt rettet mod de små grupper som har en halv times eksamination

**Comment by kaspercphbusiness** [comment]
Tak for at du spottede det - der trækkes spørgsmål ved starten af den mundtlige individuelle eksamen. For de grupper der ender på en person, så er det et samlet forløb hvor der først præsenteres, og derefter trækkes et spørgsmål.
